import './globals.css'
import Header from './components/Header'
import {Poppins} from 'next/font/google'

const poppins = Poppins({ 
  weight:['400','700'],
  subsets: ['latin'], 
})

export const metadata = {
  title: 'First Next.js App ',
  description: 'Generated by create next app',
  keywords: "SEO keywords....."
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        </body>
    </html>
  )
}
